
IPV6_NETWORK_DIRECTORY="/etc/ipv6-routing/"
IPV6_NETWORK_PREFIXES="${IPV6_NETWORK_DIRECTORY}prefix/"
IPV6_NETWORK_IFACE="${IPV6_NETWORK_DIRECTORY}iface/"
IPV6_USER_SESSION="${IPV6_NETWORK_DIRECTORY}last/"
IPV6_USE_SESSION=1
IPV6_ALLOW_PREFIX_DEGLATION=1
IPV6_NETWORK_SIZE=64

